version: 2.1

parameters:
  cache-version:
    type: string
    default: v1

executors:
  circleci:
    docker:
      - image: cimg/node:18.20

jobs:
  install-deps:
    parameters:
      exec:
        type: executor
        default: root
    executor: << parameters.exec >>
    steps:
      - checkout
      - run: whoami
      - run:
          name: Inspect versions
          command: |
            node --version
            npm --version
            yarn --version
      - restore_cache:
          name: Restore yarn cache
          keys:
            - yarn-<< pipeline.parameters.cache-version >>-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
            - yarn-<< pipeline.parameters.cache-version >>-{{ checksum "yarn.lock" }}
            - yarn-<< pipeline.parameters.cache-version >>
      - run:
          name: Setup Node
          no_output_timeout: 15m
          command:
            yarn install --no-check-cache --immutable
      - save_cache:
          name: Save yarn cache
          key: yarn-<< pipeline.parameters.cache-version >>-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - node_modules
            - .yarn/cache
            - .yarn/install-state.gz

workflows:
  main:
    jobs:
      - install-deps:
          matrix:
            parameters:
              exec:
                - circleci
