version: 2.1

parameters:
  cache-version:
    type: string
    default: v1

executors:
  root:
    docker:
      - image: kelvintaywl/cimg-node-18:root
  circleci:
    docker:
      - image: kelvintaywl/cimg-node-18:circleci

jobs:
  install-deps:
    parameters:
      exec:
        type: executor
        default: root
    executor: << parameters.exec >>
    steps:
      - checkout
      - run: whoami
      - run:
          name: Inspect versions
          command: |
            node --version
            npm --version
            yarn --version
      - restore_cache:
          name: Restore yarn cache
          keys:
            - << parameters.exec >>-yarn-<< pipeline.parameters.cache-version >>-{{ arch }}-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
            - << parameters.exec >>-yarn-<< pipeline.parameters.cache-version >>-{{ arch }}-{{ checksum "yarn.lock" }}
            - << parameters.exec >>-yarn-<< pipeline.parameters.cache-version >>-{{ arch }}
      - run:
          name: Setup Node
          no_output_timeout: 15m
          command:
            yarn install --no-check-cache --immutable
      - save_cache:
          name: Save yarn cache
          key: << parameters.exec >>-yarn-<< pipeline.parameters.cache-version >>-{{ arch }}-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "package.json" }}
          paths:
            - node_modules
            - .yarn/cache
            - .yarn/install-state.gz

workflows:
  main:
    jobs:
      - install-deps:
          matrix:
            parameters:
              exec:
                - root
                - circleci
